[package]
name = "hello_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
emath = "0.30.0"

egui_extras = "0.30.0"
eframe = "0.30.0"
egui = "0.30.0"
egui_plot = "0.30.0"

image = "0.24.8"

rand = "0.8.5"

